language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'CREATE DATABASE bookbrainz_test;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp"; CREATE SCHEMA musicbrainz; CREATE SCHEMA bookbrainz;' -d bookbrainz_test -U postgres

script:
  - python setup.py bootstrap
  - python setup.py test

notifications:
  email: false
